name: CI

on:
  pull_request:
    branches: [ master ] # Or your default branch

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version
      - name: Install dependencies
        run: npm ci # Or yarn install
      - name: Check TypeScript compilation
        run: npx tsc --noEmit

  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version
      - name: Install dependencies
        run: npm ci # Or yarn install
      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx # Adjust file extensions if needed
